<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <style>

    	/** {
    		border: 1px solid red;
    	}*/
    	
    </style>

    <title>Javascript - Tratamento de erros em JavaScript</title>
  </head>
  <body>

    <div class="container">
    	<div class="row">
    		<div class="col-md-12 m-auto d-flex justify-content-center">
    			
    		</div>
    	</div>
    </div>



    <script type="text/javascript">

        // Os tipos de try(tente) são: catch(pegar), finaly(finalizar) e throw(lançar)

        throw new Error('Página em manuntenção, por favor volte mais tarde!')

        // Em relação ao tratamento de erros em JavaScript, temos a seguinte situação: Por exemplo nós teriamos algum serviço de stream, por exemplo a Netflix, ao clicarmos para assistirmos algum filme que esteja no catáogo, irá ser feita uma requisição ao servidor htpp, retornando o filme desejado, agora podendo ser assistido no player do browser. Logo, nessa dinâmica, iremos ter um array que contém o nome e a categoria do filme.

        // De acordo com o exemplo abaixo, temos uma situação em que é possível que ocorra vários erros, isso porque, por exemplo: se o vídeo não estivesse disponível, tivesse ocorrido uma falha no servidor etc.

        var video = Array()

        video['nome'] = ['Death Note']
        video['categoria'] = ['Anime']

        function getVideo(video) {
            // Para a criação de algum erro, para podemos fazer um tratamento, iremos pedir o console.log() do array video, porém de um índice que ainda não existe, e dentro desse índice que não existe, iremos tentar acessar algum elemento que esteja dentro do array, por exemplo: console.log(video[2]['nome'])

            // Agora para o tratamento de erro, iremos utlizar o bloco de código try, então, como é um bloco de código, todo código que possa apresentar algum tipo de erro inesperado, deve estar dentro desse bloco:
            try {
                console.log(video[2]['nome'])

            } catch(e) {
                console.log('O erro foi capturado')

            } finally {
                console.log('Sempre passa por aqui (try / catch)')
            }

            // Iremos criar um outro console.log(), para conferirmos se a nossa aplicação ainda está sendo executada, ou ela simplesmente parou de funcionar após o erro.
            console.log('A aplicação não parou!')
        }

        getVideo(video)

    </script>

    



















    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>